### ISSUE TITLE
Add improvements on import errors and update library version

### ISSUE THREAD

**Issue by 3demax** [apmorton/pyhidapi#14]
There are 2 PRs that can easily improve library usability: #12 and #13
Also, the package on pypi doesn't contain fixes from master.

@apmorton Please take a look.

**Comment by apmorton** [comment]
Hello,
Thanks for your interest in this library, and sorry for the lack of maintenance on my end with regards to PRs and updates to pypi.

In any case, which PR would you like me to merge? #12 would conflict with the changes you make in #13 

IMO, #13 is not strictly an improvement if the proper `ImportError` is thrown, which was fixed by @NZSmartie some time ago, but as you mentioned never got published to pypi.

Unless you want to send in another PR I will merge #12, close #13, and bump the version on pypi.

I will wait till I hear back from you in any case.

Thanks,
Austin

**Comment by 3demax** [comment]
I have updated #13 so that it combines both.
Thank you for quick response!
Hope you can merge this now.

**Comment by 3demax** [comment]
@apmorton Is it better now?
