### ISSUE TITLE
install on Mac

### ISSUE THREAD

**Issue by jeremygray** [apmorton/pyhidapi#8]
I followed your very helpful instructions for installation, but I also needed to edit `hid.__init__.py` library_paths to include `libhidapi-iohidmanager.so`. hid 0.1.1, Mac 10.11.2

**Comment by jeremygray** [comment]
Also, there appears to be a typo in `__init__.py`

    library_paths = (
      'libhidapi-hidraw.so',
      'libhidapi-hidraw.so.0',
      'libhidapi-libusb.so',
      'libhidapi-libusb.so.0',
      'libhidusb-iohidmanager.so'    # <<==== missing comma here
      'libhidusb-iohidmanager.so.0'

**Comment by apmorton** [comment]
woops! Very sorry about this whole thing.
It took much too long for me to notice/answer this, so its likely you have moved on to something else by now anyway, but..

It looks like I broke this in `e925b4f` when providing an alternate solution for #3, and the original contributor didn't see the issue because he was working on a *nix system, not osx.

I transposed something, somehow, because `libhidusb-iohidmanager.so` does not exist (go ahead and search google for it, this git repo is the only result!).

In any case, please confirm if this fixes the issues you were having on osx and I will push an update to pypi - pending feedback from the user who reported #9 as well

**Comment by jeremygray** [comment]
That should fix things for me, thanks
